### ISSUE TITLE
Loop and Alt use the full width instead of only covering the leftmost to rightmost inner columns.

### ISSUE THREAD

**Issue by TheMightyGit** [lmika/goseq#11]
If I have 5 columns and a loop around 2 of them the outer box of the loop is the full width of the diagram. I expected it to only cover the leftmost to rightmost of the inner referenced columns. For a diagram with many loops it makes it visually very noisy when all boxes are full width.

```
One->Two:

loop: loop1
  Two->Three:
end

Three->Four:
Four->Five:
```

In the above code I would expect the loop to only encompass Two and Three. Instead it is the full width...

<img width="269" alt="Screenshot 2020-10-08 at 17 28 14" src="https://user-images.githubusercontent.com/888751/95487049-ba8f7500-098b-11eb-8177-6193b4b7cfdf.png">

(Although I'm queueing up a bunch of issues I may take a look at them myself - I just wanted to be able to track and prioritise them)

**Comment by lmika** [comment]
Yep, this is something that can improve the quality of the diagrams.  Thanks for taking a look at it, @TheMightyGit.
