### ISSUE TITLE
Random sampling vs Wallenius

### ISSUE THREAD

**Issue by TheCatalyticMicroChip** [lmika/goseq#15]
Hi,

I would like to understand the difference between Random sampling and Wallenius distribution method. I know it's explained in the manual but I still don't quite get it.

In our analysis we see more functionally relevant GO terms using the random sampling method vs Wallenius distribution, which gives functionally non-relevant GO terms to our conditions. I would appreciate any inputs.

**Comment by lmika** [comment]
Hi @MzwaneleN,

You may have opened an issue on the wrong repo.  I don't recall writing anything about "Random sampling and Wallenius distribution" in the documentation of this project.  There wouldn't be anything of this nature in goseq as I'm not at all familiar with these concepts, and I probably would not be the best person to explain it.

Thanks,

Leon
