### ISSUE TITLE
Bug in nested ALT with self referencing

### ISSUE THREAD

**Issue by NikolaiLaptevTR** [lmika/goseq#16]
This code display nesting normally
```
participant User
participant API
participant Database (icon="cylinder")

alt: [client is ready]
    API->Database: Send message
    alt: [client has ip address]
        API->Database: Send message2
    end
end
```

But when we replace `API->Database: Send message2` with `API->API: Send message2`, nested ALT become bigger than its parent ALT.
All code to reproduce a bug:
```
participant User
participant API
participant Database (icon="cylinder")

alt: [client is ready]
    API->Database: Send message
    alt: [client has ip address]
        API->API: Send message2
    end
end
```

**Comment by lmika** [comment]
Thanks for the report.  I will look into it.

**Comment by lmika** [comment]
Just to make sure we're seeing the same thing, here is what was produced when I executed the diagrams from the latest version on master:

First diagram:

![out1](https://user-images.githubusercontent.com/3238909/124032006-5a6dc100-da3b-11eb-90eb-bae249ff92af.png)

Second diagram:

![out2](https://user-images.githubusercontent.com/3238909/124032047-6a85a080-da3b-11eb-9ef3-d1f41d98dd0a.png)

Is this what you're seeing as well?

**Comment by lmika** [comment]
Ah, I see the problem. This bug may have already been fixed as part of issue #11. I will cut a new release containing the bug fix. Once that's done, please check it out and see whether the issue persists.

**Comment by NikolaiLaptevTR** [comment]
Thanks for a quick update.
The second diagram for me contains nested ALT covering User line and it crosses its parent ALT.
What you shared on a picture is what I would love it to be :-)

**Comment by lmika** [comment]
Thanks, @NikolaiLaptevTR .  May I suggest trying out version 0.0.2.  This should have the fix in place.

**Comment by NikolaiLaptevTR** [comment]
@lmika works great. Thank you very much.

**Comment by lmika** [comment]
No problem.  Thanks for the report.
