### ISSUE TITLE
can't generate ethereum's sequence diagram

### ISSUE THREAD

**Issue by feiyiban** [lmika/goseq#17]
can't generate ethereum's sequence diagram

**Comment by lmika** [comment]
Hi @feiyiban, could you send through the sequence diagram your trying to generate, as well as the `goseq` command you’re trying to run along with any error outputs you see?  Thanks.

**Comment by feiyiban** [comment]
![image](https://user-images.githubusercontent.com/15224713/142712001-fad36e59-e4b9-4630-9ace-4b7262f4a449.png)
you can try it with go-ethereum! thanks

**Comment by lmika** [comment]
Ah, I see what what you're trying to do.  It looks like you're trying to run `goseq` with a Go source file, probably to produce a sequence diagram directly from the code.  Unfortunately, `goseq` does not support this.  Instead, sequence diagrams are produce using a custom domain-specific language, which is usually (although not required to) written by hand.  Please take a look at [the Language Guide](https://github.com/lmika/goseq/wiki/LanguageGuide) for how this DSL is put together.
