### ISSUE TITLE
Provide list of icons in README.md file

### ISSUE THREAD

**Issue by blazejkrzak** [lmika/goseq#18]
**Problem:**
Lack of list of available icons
**Proposition**
Please provide list of `icon="$value"` in order to ease the work. Or just point to the file, I was searching like 10 mins and found nothing yet. 
**Gain:**
It will increase user experience with this library

**Icons I have found**
```go
var builtinIcons = map[string]ActorIcon{
        "human":    &builtinActorIcon{graphbox.StickPersonIcon(1)},
        "cylinder": &builtinActorIcon{graphbox.CylinderIcon(1)},
        "cloud":    &builtinActorIcon{graphbox.PathIcon{graphbox.CloudPathData}},
}
```

**Comment by lmika** [comment]
Hi @blazejkrzak, the list of supported icons are actually in the [Style Attribute reference](https://github.com/lmika/goseq/wiki/StyleAttributes).  I'll see what I can do about making that document more visible from the README.md.

**Comment by lmika** [comment]
Link to the Style Attribute reference has been added to README.md.
