### ISSUE TITLE
Inconsistent nullp and goseq enrichment results across operating systems

### ISSUE THREAD

**Issue by daniellembecker** [lmika/goseq#23]

**Comment by daniellembecker** [comment]
@lmika

**Comment by lmika** [comment]
Hi @daniellembecker , I'm not sure what this bug refers to. This doesn't look like something that goseq generally supports (it's a tool for generating sequence diagrams).

**Comment by daniellembecker** [comment]
Hi @lmika thank you for the response. The issue is inconsistency with the nullp and goseq functions in the goseq package. When used on different computers the package is not computing the same values using the same data, code, and functions from the goseq package
