### ISSUE TITLE
Packaging as debian package

### ISSUE THREAD

**Issue by twitchyliquid64** [lmika/goseq#8]
Heya,
 
It would be convenient for me if this was installable as a `.deb` file.

Would you let me script the generation of the `.deb` package and send you a pull request?

**Comment by lmika** [comment]
Hi @twitchyliquid64, that sounds good. Please feel free to submit a pull request with your script and I'll take a look at integrating it. Thanks for that.

**Comment by lmika** [comment]
This has been a long time coming, but .deb packages are now finally being produced as part of the release.
