### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by sasahoo** [lmika/goseq#9]
Hi,

I am trying the below commands as per **READ ME**. It is failing for all files with same syntax error. 

```
>> goseq client/manager.go -o s1.svg
goseq: client/manager.go - client/manager.go:5: syntax error
```
Please help me with this.

**Comment by lmika** [comment]
Hi @sasahoo, 

It looks like you're trying to parse a Go file.  The `goseq` command accepts a sequence diagram description file, which usually ends in ".seq" and will look something like the following:

```
Client->Server: Make request
Server->Database: Make database\nrequest
Database->Server: The result
Server->Client: The response
```

Can you let me know where in the README you got these instructions so I can correct them?

Thanks,

Leon

**Comment by sasahoo** [comment]
Thanks @lmika , Oh Ok. My mistake then. I missed something then. Would you please help me to find the commands doc how to create seq diagrams?

**Comment by lmika** [comment]
Best place to look for how to create sequence diagrams is within the [Language Guide](https://github.com/lmika/goseq/wiki/LanguageGuide).  Basically the approach is:

1. Write a text file of the sequence diagram using the DSL and save it as something, like "hello.seq".
2. Run `goseq -o hello.svg hello.seq`.  That will convert the text based DSL into an SVG image
